name = "askislamai-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
# خلي هادي خاوية هنا، وعمريها فـ Cloudflare Dashboard باش يبقى الساروت مخبي
ANTHROPIC_API_KEY = ""

# هاد الجزء ضروري باش الـ Worker يقدر يقرأ ملف index.html
[site]
bucket = "./"
